source 'https://rubygems.org'

gem 'sinatra'
gem 'logger'
gem 'json'
gem 'bson'
gem 'mongo'
gem 'mail'
gem 'pry'


group :development, :test do
	gem 'sinatra-contrib'
	gem 'sinatra-reloader'
	# Call 'byebug' anywhere in the code to stop execution and get a debugger console
	gem 'byebug'

	# Access an IRB console on exception pages or by using <%= console %> in views
	gem 'web-console', '~> 2.0'

	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	gem 'spring'
	gem 'dotenv-rails'
end

