source 'https://rubygems.org'
ruby '2.3.1'

gem 'sinatra', '~> 2.0'
gem 'logger'
gem 'json', '~> 2.1'
gem 'bson', '~> 4.2', '>= 4.2.1'
gem 'mongo', '~> 2.4', '>= 2.4.1'
gem 'mail', '~> 2.6', '>= 2.6.5'
gem 'pry', '~> 0.10.4'
gem 'rack', '~> 2.0', '>= 2.0.3'


group :development, :test do
	gem 'sinatra-contrib', '~> 2.0'
	gem 'sinatra-reloader', '~> 1.0'
	# Call 'byebug' anywhere in the code to stop execution and get a debugger console
	gem 'byebug'

	# Access an IRB console on exception pages or by using <%= console %> in views
	gem 'web-console', '~> 2.0'

	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	gem 'spring'
end

group :development, :test, :production do
	gem 'dotenv', '~> 2.2', '>= 2.2.1'
end